title: 
logo: /assets/img/logo.png
description: Hi, I am Kristle. I am glad you are here! I created this page to demonstrate my skills in data analytics and share some of the projects I have worked on. Take your time exploring, and don’t hesitate to reach out. I am always open to conversations, feedback, or new opportunities. Here is my Linkedin account if ever you want to connect: https://ph.linkedin.com/in/kristle-anyaya
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
