title: 
logo: /assets/img/logo.png
description: Hi, I'm Kristle. I'm glad you're here! I put together this page to demonstrate my skills and share some of the projects I've worked on. Take your time exploring, and don’t hesitate to reach out. I'm always open to conversations, feedback, or new opportunities.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
