title: 
logo: /assets/img/logo.png
description: Hi, I&aposm Kristle. I&aposm glad you&aposre here! I put this page together to demonstrate my skills in data analytics and feature some of the projects I’ve worked on. Take your time exploring, and don’t hesitate to reach out. I&aposm always open to conversations, feedback, or new opportunities. Here&aposs my Linkedin account if ever you want to connect: https://ph.linkedin.com/in/kristle-anyaya
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
